import React, { useState, useEffect } from 'react';
import { Shield, AlertTriangle, CheckCircle2, Zap, Layers, RefreshCw, Loader2, ArrowUpRight, Download, Copy, Check, FileText } from 'lucide-react';
import { AnalysisAPI } from '../services/api';

export default function FindingsPanel({ repository, onOpenFileWithLines }) {
  const [findings, setFindings] = useState([]);
  const [loading, setLoading] = useState(false);
  const [selectedCategory, setSelectedCategory] = useState('ALL');
  const [copiedId, setCopiedId] = useState(null);

  const loadFindings = async () => {
    if (!repository) return;
    setLoading(true);
    try {
      const res = await AnalysisAPI.getFindings(repository.id);
      setFindings(res.data || []);
    } catch (err) {
      console.error("Failed to load findings:", err);
    } finally {
      setLoading(false);
    }
  };

  const triggerNewAnalysis = async () => {
    if (!repository) return;
    setLoading(true);
    try {
      const res = await AnalysisAPI.run({
        repositoryId: repository.id,
        categories: ["ARCHITECTURE", "SECURITY", "PERFORMANCE", "TESTING"]
      });
      setFindings(res.data || []);
    } catch (err) {
      console.error("Failed to run analysis:", err);
    } finally {
      setLoading(false);
    }
  };

  const handleExportMarkdown = () => {
    if (findings.length === 0) return;
    let md = `# Specialist Code Audit Report: ${repository?.name || 'Repository'}\n`;
    md += `*Generated by AI Codebase Architect on ${new Date().toLocaleDateString()}*\n\n`;
    md += `## Executive Summary\nTotal Findings: ${findings.length}\n\n`;

    findings.forEach((f, idx) => {
      md += `### ${idx + 1}. [${f.severity}] ${f.title}\n`;
      md += `- **Category**: ${f.category}\n`;
      if (f.filePath) md += `- **File**: \`${f.filePath}:${f.lineNumber || 1}\`\n`;
      md += `- **Finding**: ${f.finding}\n`;
      if (f.recommendation) md += `- **Recommendation**: ${f.recommendation}\n\n`;
    });

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `audit-report-${repository?.name || 'repo'}-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyPatch = (finding) => {
    const patch = `--- a/${finding.filePath || 'file'}\n+++ b/${finding.filePath || 'file'}\n@@ -${finding.lineNumber || 1} @@\n# Remediation recommendation:\n# ${finding.recommendation || finding.finding}`;
    navigator.clipboard.writeText(patch);
    setCopiedId(finding.id || finding.title);
    setTimeout(() => setCopiedId(null), 2000);
  };

  useEffect(() => {
    loadFindings();
  }, [repository]);

  const filteredFindings = selectedCategory === 'ALL'
    ? findings
    : findings.filter(f => f.category === selectedCategory);

  const getSeverityBadge = (sev) => {
    switch (sev) {
      case 'CRITICAL':
        return <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-rose-500/20 text-rose-400 border border-rose-500/30">CRITICAL</span>;
      case 'HIGH':
        return <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-amber-500/20 text-amber-400 border border-amber-500/30">HIGH</span>;
      case 'MEDIUM':
        return <span className="px-2 py-0.5 rounded-full text-[10px] font-medium bg-blue-500/20 text-blue-400 border border-blue-500/30">MEDIUM</span>;
      default:
        return <span className="px-2 py-0.5 rounded-full text-[10px] font-medium bg-slate-500/20 text-slate-400 border border-slate-500/30">LOW</span>;
    }
  };

  return (
    <div className="flex-1 bg-[#070B16] flex flex-col h-full min-h-0 overflow-hidden border-r border-surfaceBorder select-none">
      {/* Header */}
      <div className="h-11 bg-surface/90 backdrop-blur-md border-b border-surfaceBorder flex items-center justify-between px-4 shrink-0 z-10">
        <div className="flex items-center space-x-2.5 text-xs">
          <div className="p-1 rounded-md bg-rose-500/20 text-rose-400">
            <Shield className="w-4 h-4" />
          </div>
          <span className="font-bold text-white text-sm">Specialist Audit Findings</span>
          <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-surfaceLight border border-surfaceBorder text-slate-400 font-semibold">
            {filteredFindings.length} Issues
          </span>
        </div>

        <div className="flex items-center space-x-2">
          {findings.length > 0 && (
            <button
              onClick={handleExportMarkdown}
              className="flex items-center space-x-1 text-xs text-slate-300 hover:text-white px-2.5 py-1 bg-surfaceLight hover:bg-surfaceBorder border border-surfaceBorder rounded-lg transition font-medium"
              title="Download Audit Report (Markdown)"
            >
              <Download className="w-3.5 h-3.5 text-primary-400" />
              <span>Export Report</span>
            </button>
          )}

          <button
            onClick={triggerNewAnalysis}
            disabled={loading || !repository}
            className="flex items-center space-x-1.5 text-xs text-white px-3 py-1 bg-primary-600 hover:bg-primary-500 rounded-lg transition shadow-md shadow-primary-600/20 disabled:opacity-50 font-semibold"
          >
            {loading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <RefreshCw className="w-3.5 h-3.5" />}
            <span>Run Deep Audit</span>
          </button>
        </div>
      </div>

      {/* Category Filter Tabs */}
      <div className="flex border-b border-surfaceBorder px-4 py-2 bg-surfaceLight/30 space-x-2 text-xs shrink-0 overflow-x-auto custom-scrollbar">
        {['ALL', 'ARCHITECTURE', 'SECURITY', 'PERFORMANCE', 'TESTING'].map(cat => (
          <button
            key={cat}
            onClick={() => setSelectedCategory(cat)}
            className={`px-3 py-1 rounded-lg text-[11px] font-mono font-medium transition shrink-0 ${
              selectedCategory === cat
                ? 'bg-primary-600 text-white shadow-md shadow-primary-600/30'
                : 'text-slate-400 hover:text-white hover:bg-surfaceLight'
            }`}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* Findings List Feed */}
      <div className="flex-1 min-h-0 overflow-y-auto p-4 space-y-3.5 select-text text-xs custom-scrollbar">
        {loading ? (
          <div className="flex flex-col items-center justify-center py-16 text-slate-400">
            <Loader2 className="w-8 h-8 animate-spin text-primary-400 mb-3" />
            <span className="font-medium text-slate-300">Auditing Architecture, Security, Performance & Test Coverage...</span>
            <span className="text-[11px] text-slate-500 mt-1">Inspecting AST call graphs and invariant rules</span>
          </div>
        ) : filteredFindings.length === 0 ? (
          <div className="text-center py-16 text-slate-500">
            <CheckCircle2 className="w-10 h-10 text-emerald-500/60 mx-auto mb-3" />
            <p className="font-semibold text-slate-300 text-sm">No critical findings recorded yet.</p>
            <p className="text-xs text-slate-500 mt-1">Click "Run Deep Audit" to trigger multi-perspective specialist inspection.</p>
          </div>
        ) : (
          filteredFindings.map((finding) => {
            const findingKey = finding.id || finding.title;
            const isCopied = copiedId === findingKey;

            return (
              <div
                key={findingKey}
                className="p-4 bg-surfaceLight/30 border border-surfaceBorder rounded-2xl space-y-2.5 hover:border-primary-500/40 transition shadow-lg"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-2.5">
                    {getSeverityBadge(finding.severity)}
                    <span className="font-bold text-white text-[13px]">{finding.title}</span>
                  </div>
                  <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-surface border border-surfaceBorder text-slate-400 font-semibold">
                    {finding.category}
                  </span>
                </div>

                <p className="text-slate-300 leading-relaxed text-[12px]">{finding.finding}</p>

                {finding.filePath && (
                  <div
                    onClick={() => onOpenFileWithLines(finding.filePath, finding.lineNumber || 1, (finding.lineNumber || 1) + 15)}
                    className="flex items-center space-x-1.5 text-[11px] font-mono text-primary-400 hover:text-primary-300 cursor-pointer pt-1"
                  >
                    <span>📍 {finding.filePath}{finding.lineNumber ? `:${finding.lineNumber}` : ''}</span>
                    <ArrowUpRight className="w-3.5 h-3.5" />
                  </div>
                )}

                {finding.recommendation && (
                  <div className="bg-[#0A1024] border border-primary-500/30 p-3 rounded-xl text-slate-300 space-y-1.5">
                    <div className="flex items-center justify-between">
                      <span className="font-semibold text-primary-400 text-[11px] uppercase tracking-wider flex items-center space-x-1">
                        <Zap className="w-3.5 h-3.5" />
                        <span>Recommended Remediation:</span>
                      </span>
                      <button
                        onClick={() => handleCopyPatch(finding)}
                        className="flex items-center space-x-1 text-[10.5px] font-mono text-slate-400 hover:text-white px-2 py-0.5 bg-surfaceLight hover:bg-surfaceBorder rounded border border-surfaceBorder transition"
                      >
                        {isCopied ? <Check className="w-3 h-3 text-accent" /> : <Copy className="w-3 h-3" />}
                        <span>{isCopied ? 'Patch Copied' : 'Copy Patch'}</span>
                      </button>
                    </div>
                    <p className="text-[11.5px] leading-relaxed text-slate-200">{finding.recommendation}</p>
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
